name: Portal V1 CD

on: 
  push:
    branches:
      - main
    paths:
      - .github/workflows/portal-v1-cd.yaml- .github/workflows/portal-v1-cd.yaml
      - portal-v1/**
      - '!portal-v1/**.md'

defaults:
  run:
    working-directory: portal-v1

jobs:
  deploy:
    name: Deploy to Cloudflare Pages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      statuses: write
    timeout-minutes: 10
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4
      
      - id: setup-node
        name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: npm
      
      - id: install
        name: Install
        run: npm ci

      - id: build
        name: Build
        run: npm run build

      - id: deploy
        name: Deploy
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: portal-v1
          directory: public
          branch: main
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: 3

      - name: Attach Deployed URL
        uses: actions/github-script@v7
        with:
          script: |
            const sha = context.payload.pull_request?.head.sha ?? context.sha;
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              context: 'Cloudflare Pages',
              description: 'Cloudflare Pages deployment',
              state: 'success',
              sha,
              target_url: "${{ steps.deploy.outputs.url }}",
            });
