name: Portal V1 CD

on: 
  push:
    branches:
      - main
    paths:
      - .github/workflows/portal-v1-cd.yaml
      - portal-v1/**
      - '!portal-v1/**.md'

jobs:
  deploy:
    name: Deploy to Cloudflare Pages
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/portal-v1
    permissions:
      contents: read
      deployments: write
      statuses: write
    timeout-minutes: 10
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4
      
      - id: setup-node
        name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: npm
          cache-dependency-path: ${{ github.workspace }}/portal-v1/package-lock.json
      
      - id: install
        name: Install
        run: npm ci

      - id: build
        name: Build
        run: npm run build

      - id: deploy
        name: Deploy
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: portal-v1
          directory: build/client
          workingDirectory: ${{ github.workspace }}/portal-v1
          branch: main
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: 3
