name: tech_push
on:
  pull_request:
    paths:
      - tech/**
    branches:
      - main
      - dev
      - debug
      - feature/*
      - fix/*
      - refactor/*
      - inspect

defaults:
  run:
    working-directory: tech

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          check-latest: true
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - name: Install dependencies
        run: npm ci
      - name: Setup Reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

  textlint:
    name: Use textlint
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodule: true
      - name: Lint Articles
        run: npx textlint -f checkstyle article/**/*.md | reviewdog -f=checkstyle -name=textlint -reporter=github-pr-review # TODO: config ファイル化
